runtime: python310

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: '6a449b4d7e2f8c6eb5f07e5a256638f1'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10